import { capability, type CapabilityContext, type CapabilityResult } from "../lib/broker.ts";

interface AnswerInput {
  question: string;
}

/** A short answer from web results with citations, generated by the search provider (Tavily → Exa). */
export default async function answer(input: AnswerInput, ctx: CapabilityContext): Promise<CapabilityResult> {
  return capability(ctx, "web.answer", { query: input.question });
}
