#!/usr/bin/env node
/**
 * Prepares the LOCAL Cloudflare environment used by `wrangler dev` (no Cloudflare account needed):
 *
 *   1. creates apps/registry/.dev.vars with ADMIN_TOKEN_SHA256 (and the matching plaintext admin
 *      token in apps/registry/.dev.admin-token) if they do not exist — both git-ignored;
 *   2. applies D1 migrations to the local D1 database (`wrangler d1 migrations apply --local`);
 *   3. publishes skills/* into local D1 + R2 through the same RegistryService, using wrangler's
 *      getPlatformProxy() to reach the local bindings.
 */
import { spawnSync } from "node:child_process";
import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { generateToken, hashToken } from "./auth.js";
import { APP_ROOT, REPO_ROOT, WRANGLER_CONFIG } from "./paths.js";
import { seedDirectories } from "./seed.js";
import { RegistryService } from "./service.js";
import { artifactStoreFor, d1Database, type Env } from "./worker.js";

const DEV_VARS = join(APP_ROOT, ".dev.vars");
const ADMIN_TOKEN_FILE = join(APP_ROOT, ".dev.admin-token");

async function ensureDevVars(): Promise<void> {
  if (existsSync(DEV_VARS) && readFileSync(DEV_VARS, "utf8").includes("ADMIN_TOKEN_SHA256=")) {
    console.log(`✓ ${DEV_VARS} exists`);
    return;
  }
  const token = generateToken().replace(/^splice_/, "splice_admin_");
  writeFileSync(DEV_VARS, `# Local development only. Generated by worker-setup.\nADMIN_TOKEN_SHA256=${await hashToken(token)}\n`);
  writeFileSync(ADMIN_TOKEN_FILE, token + "\n", { mode: 0o600 });
  console.log(`✓ created ${DEV_VARS}`);
  console.log(`✓ local admin token saved to ${ADMIN_TOKEN_FILE}`);
}

function applyMigrations(): void {
  const wrangler = join(REPO_ROOT, "scripts", "wrangler.mjs");
  const result = spawnSync(process.execPath, [wrangler, "d1", "migrations", "apply", "splice-registry", "--local", "-c", WRANGLER_CONFIG], {
    cwd: APP_ROOT,
    stdio: "inherit",
    env: { ...process.env, CI: "1" },
  });
  if (result.status !== 0) throw new Error("wrangler d1 migrations apply failed");
  console.log("✓ local D1 migrations applied");
}

async function seedLocalWorker(): Promise<void> {
  process.env.WRANGLER_SEND_METRICS = "false";
  const { getPlatformProxy } = await import("wrangler");
  // Same state directory `wrangler dev` / `wrangler d1 --local` use for this config.
  const proxy = await getPlatformProxy<Env>({ configPath: WRANGLER_CONFIG, persist: { path: join(APP_ROOT, ".wrangler", "state", "v3") } });
  try {
    const service = new RegistryService(d1Database(proxy.env.DB), artifactStoreFor(proxy.env));
    const skills = join(REPO_ROOT, "skills");
    const dirs = readdirSync(skills)
      .map((n) => join(skills, n))
      .filter((p) => statSync(p).isDirectory());
    for (const line of await seedDirectories(service, dirs)) console.log(`✓ ${line}`);
  } finally {
    await proxy.dispose();
  }
}

await ensureDevVars();
applyMigrations();
await seedLocalWorker();
console.log("\nNext: npm run registry:worker:dev   (serves http://127.0.0.1:8787)");
